version: "3"

volumes:
  mysql_data:
      driver: local


services:  
  mariadb:
      image: mariadb
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      # Copy-pasted from https://github.com/docker-library/mariadb/issues/94
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--silent"]
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: mariadb
        DB_ADDR: mariadb
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      ports:
        - 8080:8080
      depends_on:
        - mariadb

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "8000:80"
    networks:
      - products

  product-service:
    build:
      context: ./backend/product_service
    container_name: product_service
    command: npm start
    restart: always
    ports:
      - "5100:5100"
    environment:
      - PORT=5100
    networks:
      - products
  order-service:
    build:
      context: ./backend/order_service
    container_name: order_service
    command: npm start
    restart: always
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
    networks:
      - products
networks:
  products: